CREATE DATABASE IF NOT EXISTS users DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE TABLE IF NOT EXISTS postsdata (
added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
imgurl LONGTEXT NOT NULL,
message LONGTEXT NOT NULL,
likesCount LONGTEXT NOT NULL,
comments LONGTEXT NOT NULL,
userphoto LONGTEXT NOT NULL
);